---
# Ansible Playbook to upgrade Cisco IOS 
 
- name: Upgrade CISCO IOS 
  hosts: SWITCHES
 
  vars:
    upgrade_ios_version: 12.2(55)SE12
 
  tasks:
    - name: CHECK CURRENT VERSION
      ios_facts:
 
    - debug:
        msg:
        - "Current version is {{ ansible_net_version }}"
        - "Upgrade image is 12.2.55-SE12"
 
    - debug:
        msg:
        - "Image is not compliant and will be upgraded"
 
      when: ansible_net_version != upgrade_ios_version
